### ISSUE TITLE
::create() ignores default values of Blueprint.

### ISSUE THREAD

**Issue by alexanderhorner** [ryangjchandler/orbit#82]
If my Model has a column with a default value and I create a new Instance, it doesn't get saved in file. 

My Blueprint inside the Model:

```php
public static function schema(Blueprint $table)
{
    $table->string('title');
    $table->string('link');
    $table->string('author')->default('Max Mustermann');
}
```

The create Method:

```php
Article::create([
    'title' => 'Test',
    'link' => 'test-link'
]);
```

The generated file:

```yml
---
title: Test
link: test-link
---
```

What I expect: 

```yml
---
title: Test
link: test-link
author: Max Mustermann
---
```

It's weird because the sqlite cache actually works like expected and fills the author column with the default value. But the next time it's refreshed, I get a `Integrity constraint violation: 19 NOT NULL constraint failed. articles.author`

Feature request related to this issue: If a NOT NULL field has a default, don't make it mandatory to have it set in the file. Just return the default if it's missing.

Good package though, big fan of it.
